### PR TITLE
separating the damage anim from the real damage

### PR DESCRIPTION
**Pull request by n0deee**

### CODE REVIEW

**Comment by n0deee** [comment]
Separating the damage anim from the actual damage

**Comment by n0deee** [comment]
This also fix the [Issue #30](https://github.com/ABCxFF/diepcustom/issues/30)

**Comment by Nul-led** [comment]
Lgtm

**Comment by Altanis** [comment]
lgtm, nice work!

**Review by BlueCannonBall — APPROVED** [review]
Looks good to me!

**Review by ABCxFF — APPROVED** [review]
Looks great, nice! Merging now

**Pull request merged**
