### PR TITLE
Minor patches(#44,#49,#50,#2, #4)

### LINKED ISSUE #2: Constant `OUTPUT_BUFFER` capacity can cause crashes
Once compressor is built (waiting on #1), deal with this maximum output buffer capacity.

https://github.com/ABCxFF/diepcustom/blob/main/src/Coder/Writer.ts#L25

As of now, server crashes if u see enough objects be made at once (only happens when on high FOV so it doesn't matter much anyway).

### PR DESCRIPTION
**Pull request by ABCxFF**
### Why:

Closes #2, #44, #49, and #50.

### Summarize what's being changed (include any screenshots, code, or other media if available):

1. #2) Added 00 packet chunking (idea by Nulled) to split up larger packets into multiple smaller ones. Along with that, made the `OUTPUT_BUFFER` resize if running out of space.
2. #44) Makes AI check if the target's sides != 0, before continuing to use it as a target.
3. #49) Set the spectator tank to actually use the invisibility meta data described earlier (someone forgot to do this previously)
4. #50) Set fallen bosses to have no team, and set non teamed dominators to default to the Arena
5. #4) Calculates barrel pos correctly - algorithms were off
### Confirm the following:
- [x] I have tested these changes (by compiling, running, and playing) and have seen no differences in gameplay

### CODE REVIEW

**Comment by Nul-led** [comment]
Possible Improvements for #2:
- using Buffer.poolSize to make use of preallocated memory making the creation of new typed arrays faster (needs to be adjusted to current typesize i think)
- (optional) adding a config option to adjust the poolSize

**Comment by ABCxFF** [comment]
Ah smart. Was also just thinking of generally switching to Buffers instead of Uint8Array and views

**Comment by Nul-led** [comment]
Yup LGTM

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
seems good

**Review by c86ec23b-fef1-4979-b2fa-b9adc351b8cc — APPROVED** [review]
good

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
it has bug: console is spammed with possible desync error

**Comment by Nul-led** [comment]
I suppose we cant do much about that, apart from
a) collecting & merging 00 packets on the client
b) disabling console output

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
@Nul-led only the camera file causes that bug not the writer it seems

**Comment by supahero1** [comment]
As for #2, you can use:
```js
socket.send(data, { fin: false })
```
to send a partial message without actually splitting it into a separate websocket message (all of them will be merged into one on the other side once `fin: true` is set, or if the second argument is not given, since then `fin` is set to `true` by default). There's no need to dynamically resize the buffer or anything, just check if we're about to write past the end of it, and send the frame.

**Comment by Altanis** [comment]
LGTM

quick thing, invisible entities don't get sent to the client right

**Comment by ABCxFF** [comment]
> As for #2, you can use:
> 
> ```js
> socket.send(data, { fin: false })
> ```
> 
> to send a partial message without actually splitting it into a separate websocket message (all of them will be merged into one on the other side once `fin: true` is set, or if the second argument is not given, since then `fin` is set to `true` by default). There's no need to dynamically resize the buffer or anything, just check if we're about to write past the end of it, and send the frame.

That's awesome, thanks for letting me know. I'll add in later today / tomorrow

**Review by c86ec23b-fef1-4979-b2fa-b9adc351b8cc — CHANGES_REQUESTED** [review]
good, but fix the entity desync console message problem

**Comment by ABCxFF** [comment]
Should be fixed now @c86ec23b-fef1-4979-b2fa-b9adc351b8cc

**Comment by Nul-led** [comment]
LGTM

**Pull request merged**
