### PR TITLE
Cleanup + minor rerouting

### PR DESCRIPTION
**Pull request by ABCxFF**
### Why:

Just general cleanup, also a boss bug fix.

### Summarize what's being changed (include any screenshots, code, or other media if available):

Client.toString() added, boss interval fixed, index.ts reorganized, created `GuardAddon`  class, 
### Confirm the following:
- [x] I have tested these changes (by compiling, running, and playing) and have seen no differences in gameplay

### CODE REVIEW

**Comment by BlueCannonBall** [comment]
Is it worth it to hash IP addresses? It's very easy to "unhash" IPv4 addresses.

**Comment by Altanis** [comment]
for the sake of security, hashing would be preferable even if it could be bruteforced. the hashing algorithm, to my knowledge, doesnt deoptimize performance

**Comment by BlueCannonBall** [comment]
It's so easy to brute force. Not only that, but it is trivial for a bad server owner to remove hashing. I wouldn't bet on clients using IPv6, as I've only ever seen it on a VPS and on mobile data on a few occasions.

**Review by BlueCannonBall — CHANGES_REQUESTED** [review]
Remove the useless IP address hashing.

**Pull request merged**
